# Generated by Django 2.2.7 on 2019-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('teamCount', models.PositiveIntegerField()),
                ('membersPerTeam', models.PositiveIntegerField()),
                ('typeOfContest', models.PositiveIntegerField(default=0)),
                ('numberOfRounds', models.PositiveIntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('canVote', models.BooleanField(default=False)),
                ('isStarted', models.BooleanField(default=False)),
                ('currentRound', models.PositiveIntegerField(default=0)),
                ('currentSeries', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
