# Generated by Django 2.2.7 on 2019-11-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='categoryName',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='postedBy',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='teamName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='contest',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
