# Generated by Django 2.2.7 on 2019-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
