# Generated by Django 2.2.7 on 2019-11-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=40)),
                ('numberOnBack', models.PositiveIntegerField()),
                ('isDisqualified', models.BooleanField(default=False)),
                ('isStillCompeting', models.BooleanField(default=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='contestapp.Contest')),
            ],
        ),
    ]
