# Generated by Django 2.2.7 on 2019-11-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0002_auto_20191110_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
