# Generated by Django 2.2.7 on 2019-11-16 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officialSurname', models.CharField(max_length=25)),
                ('officialName', models.CharField(max_length=25)),
                ('stageName', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='contestapp.Team')),
            ],
        ),
    ]
