# Generated by Django 2.2.7 on 2019-11-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0003_auto_20191110_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='contestapp.Team'),
        ),
    ]
