# Generated by Django 2.2.7 on 2019-11-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0003_auto_20191110_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='slug',
        ),
        migrations.AddField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
