# Generated by Django 2.2.7 on 2019-11-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0004_auto_20191110_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(default='def', max_length=50),
            preserve_default=False,
        ),
    ]
