# Generated by Django 2.2.7 on 2019-11-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0004_auto_20191111_1112'),
        ('contestapp', '0004_auto_20191111_1640'),
    ]

    operations = [
    ]
