# Generated by Django 2.2.7 on 2019-11-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0005_merge_20191111_1845'),
        ('contestapp', '0005_merge_20191111_1826'),
    ]

    operations = [
    ]
