# Generated by Django 2.2.7 on 2019-11-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0006_merge_20191112_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='grade',
            name='roundNumber',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
